version: '3.1'

services:
  php-apache-environment:
    container_name: php-apache
    build:
        context: ./app
        dockerfile: Dockerfile
    depends_on:
        - db
    volumes:
        - ./app:/var/www/html/
    ports:
        - 8081:80
    networks:
      - financas
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: financas
      MYSQL_USER: app_financas
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - financas
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      MYSQL_USERNAME: 'app_financas'
    networks:
      - financas

networks:
  financas:
    driver: bridge
volumes:
  my-db: